**Import các thư viện cần thiết**

In [52]:
import pandas as pd;
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN

**Tìm hiểu các trường dữ liệu**

In [53]:
df = pd.read_csv("./Dataset_v1.9.csv")
df.dropna(inplace=True)
df.head()

,id,Label,mint_count_per_week,burn_count_per_week,mint_ratio,swap_ratio,burn_ratio,mint_mean_period,swap_mean_period,burn_mean_period,swap_in_per_week,swap_out_per_week,swap_rate,lp_avg,lp_std,lp_creator_holding_ratio,lp_lock_ratio,token_burn_ratio,token_creator_holding_ratio,number_of_token_creation_of_creator
0,0x3cd1c0b98be4451ca51265bbaeb76cf7b31e1c02,False,44.071475,16.466820,0.148132,0.796520,0.055348,0.034508,0.074894,0.221980,100.871903,136.103828,0.741002,0.119760,0.126458,0.000000e+00,0.000000,0.000000e+00,1.302617e-01,1
1,0x0c52de7bb69edd144d58d772fab1cd196919f5ef,False,13.813171,6.316279,0.169770,0.752600,0.077630,0.040580,0.050907,0.083953,42.502064,18.732391,2.266527,0.332226,0.431320,0.000000e+00,0.000000,4.000000e-07,1.000000e-08,1
2,0xa00d47b4b304792eb07b09233467b690db847c91,False,27.366327,17.779613,0.068019,0.887790,0.044191,0.131459,0.384409,0.191228,165.965722,191.224332,0.867757,0.377358,4.649864,0.000000e+00,0.064726,0.000000e+00,0.000000e+00,1
3,0x114e40ba90e9d8b002bc6936e3299daa393017bb,False,10.559028,1.912477,0.056257,0.933553,0.010189,0.036312,0.077704,0.140362,90.398212,84.822399,1.065397,0.467290,4.754048,1.480000e-08,0.693921,3.748588e-03,0.000000e+00,1
4,0x40829a59080a12f16bb8fba22354a6a42c810aab,False,9.662390,6.450369,0.024123,0.959774,0.016104,0.088733,0.206316,0.171454,204.911119,179.530891,1.141202,0.476190,5.466877,0.000000e+00,0.790202,0.000000e+00,1.000000e-08,1

**Từ dữ liệu bên trên có thể thấy có các trường:**
- Id: địa chỉ ví / contract
- Label: Được thực hiện trong 1 khoảng thời gian giới hạn, dựa trên uniswapV2
    + True = Scam token tính từ giao dịch đầu đến khi xảy ra rug-pull
    + False = Normal token (hoặc không phải rug-pull) tính từ giao dịch đầu đến lần quét (lấy data) cuối cùng
- min_count_per_week: số lượng token phát hành mới của contract trong tuần
- burn_count_per_week: số lượng token bị đốt mỗi tuần
- mint_ratio: tỷ lệ phát hành
- swap_ratio: tỷ lệ trao đổi giữa token và stablecoin (có thể là usd, ...)
- mint_mean_period: thời gian trung bình phát hành token
- swap_mean_period: thời gian trung bình giữa các lần trao đổi token
- burn_mean_period: thời gian trung bình giữa các lần đốt token
- swap_in_per_week: số lượng token trao đổi sang stablecoin / tuần
- swap_out_per_week: số lượng token được stablecoin đổi thành / tuần
- swap_rate: Tỷ giá trao đổi giữa token và stablecoin đó
- lp_avg: giá trị thanh khoản trung bình
- lp_std: độ lệch chuẩn của thanh khoản
- lp_creator_holding_ratio: tỷ lệ thanh khoản của người tạo ra đang nắm giữ
- lp_lock_ratio: tỷ lệ thanh khoản được khỏa trong smart contract
- token_burn_ratio: tỷ lệ token đang bị đốt
- token_creator_holding_ratio: tỷ lệ token mà người tạo ra đang nắm giữ
- number_of_token_creation_of_creator: tổng số token được tạo bởi người tạo token

**Chuyển Label của dữ liệu từ true - false sang 0 - 1**

In [54]:
label_encoder = LabelEncoder()
df["Label"] = label_encoder.fit_transform(df["Label"])
df.head()

,id,Label,mint_count_per_week,burn_count_per_week,mint_ratio,swap_ratio,burn_ratio,mint_mean_period,swap_mean_period,burn_mean_period,swap_in_per_week,swap_out_per_week,swap_rate,lp_avg,lp_std,lp_creator_holding_ratio,lp_lock_ratio,token_burn_ratio,token_creator_holding_ratio,number_of_token_creation_of_creator
0,0x3cd1c0b98be4451ca51265bbaeb76cf7b31e1c02,0,44.071475,16.466820,0.148132,0.796520,0.055348,0.034508,0.074894,0.221980,100.871903,136.103828,0.741002,0.119760,0.126458,0.000000e+00,0.000000,0.000000e+00,1.302617e-01,1
1,0x0c52de7bb69edd144d58d772fab1cd196919f5ef,0,13.813171,6.316279,0.169770,0.752600,0.077630,0.040580,0.050907,0.083953,42.502064,18.732391,2.266527,0.332226,0.431320,0.000000e+00,0.000000,4.000000e-07,1.000000e-08,1
2,0xa00d47b4b304792eb07b09233467b690db847c91,0,27.366327,17.779613,0.068019,0.887790,0.044191,0.131459,0.384409,0.191228,165.965722,191.224332,0.867757,0.377358,4.649864,0.000000e+00,0.064726,0.000000e+00,0.000000e+00,1
3,0x114e40ba90e9d8b002bc6936e3299daa393017bb,0,10.559028,1.912477,0.056257,0.933553,0.010189,0.036312,0.077704,0.140362,90.398212,84.822399,1.065397,0.467290,4.754048,1.480000e-08,0.693921,3.748588e-03,0.000000e+00,1
4,0x40829a59080a12f16bb8fba22354a6a42c810aab,0,9.662390,6.450369,0.024123,0.959774,0.016104,0.088733,0.206316,0.171454,204.911119,179.530891,1.141202,0.476190,5.466877,0.000000e+00,0.790202,0.000000e+00,1.000000e-08,1

**Kiểm tra dataset có bao nhiêu dữ liệu được gán nhãn rug-pull và non rug-pull**

In [55]:
df['Label'].value_counts()

1    16462
0     1834
Name: Label, dtype: int64

**Loại bỏ cột id và label để tạo ra bộ dữ liệu huấn luyện và test**

In [56]:
features = df.drop(['Label', 'id'], axis=1)
target = df['Label']
(x_train, x_test, y_train, y_test) = train_test_split(features, target, test_size=0.2, random_state=42)

**Sử dụng mô hình KNN để huấn luyện mô hình và độ chính xác của mô hình**

In [57]:
kneighbors = KNeighborsClassifier()

# Huấn luyện mô hình
kneighbors.fit(x_train, y_train)
y_predict = kneighbors.predict(x_test) 
print(accuracy_score(y_true=y_test, y_pred=y_predict))

0.9456284153005464

**Sử dụng mô hinh random forest để huấn luyện và độ chính xác của mô hình**

In [59]:

random_forest = RandomForestClassifier()
random_forest.fit(x_train, y_train)
y_predict_random_forest = random_forest.predict(x_test)
print(accuracy_score(y_true=y_test, y_pred=y_predict_random_forest))

0.98224043715847

**Sử dụng mô hình phân cụm để phân thành 2 cụm và kiểm tra các cụm có bao nhiêu thành phần**

In [71]:

kmeans = KMeans(n_clusters=2) # Do cần tìm 2 cụm rugpull và non rugpull
kmeans_clusters = kmeans.fit(features)
pd.Series(kmeans_clusters.labels_).value_counts()

0    18282
1       14
dtype: int64

**Sử dụng DBSCAN để phân cụm dữ liệu và kiểm tra có bao nhiêu cụm được tạo thành**

In [72]:
dbscan = DBSCAN()
dbscan_cluster = dbscan.fit(features)
pd.Series(dbscan_cluster.labels_).value_counts()

-1      11972
 46       218
 32       193
 38       151
 5        129
        ...
 130        5
 274        5
 236        5
 262        5
 219        4
Length: 279, dtype: int64

**Sử dụng phân phối gaussian để phân cụm và tổng số các thành phần mỗi cụm**

In [75]:
from sklearn.mixture import GaussianMixture

# Tạo mô hình GMM với số lượng cụm là 2 (có thể điều chỉnh theo yêu cầu của bạn)
gmm_model = GaussianMixture(n_components=2)
gmm_model.fit(features)
gmm_clusters = gmm_model.predict(features)
pd.Series(gmm_clusters).value_counts()

0    13561
1     4735
dtype: int64

In [1]:
!pip install transformers

Defaulting to user installation because normal site-packages is not writeable
Collecting transformers
  Downloading transformers-4.36.1-py3-none-any.whl.metadata (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.8/126.8 kB 1.7 MB/s eta 0:00:00a 0:00:01
Collecting filelock (from transformers)
  Downloading filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting huggingface-hub<1.0,>=0.19.3 (from transformers)
  Downloading huggingface_hub-0.19.4-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /home/ntkong/.local/lib/python3.10/site-packages (from transformers) (1.22.2)
Requirement already satisfied: packaging>=20.0 in /home/ntkong/.local/lib/python3.10/site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from transformers) (5.4.1)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2023.10.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: requests in /home/ntkong/.local/lib/python3.10/site-packages (from transformers) (2.27.1)
Collecting tokenizers<0.19,>=0.14 (from transformers)
  Downloading tokenizers-0.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.3.1 (from transformers)
  Downloading safetensors-0.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting tqdm>=4.27 (from transformers)
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 2.9 MB/s eta 0:00:00
Collecting fsspec>=2023.5.0 (from huggingface-hub<1.0,>=0.19.3->transformers)
  Downloading fsspec-2023.12.2-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ntkong/.local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (4.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ntkong/.local/lib/python3.10/site-packages (from requests->transformers) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/ntkong/.local/lib/python3.10/site-packages (from requests->transformers) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ntkong/.local/lib/python3.10/site-packages (from requests->transformers) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /home/ntkong/.local/lib/python3.10/site-packages (from requests->transformers) (3.3)
Downloading transformers-4.36.1-py3-none-any.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 7.1 MB/s eta 0:00:0000:0100:01
Downloading huggingface_hub-0.19.4-py3-none-any.whl (311 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.7/311.7 kB 9.7 MB/s eta 0:00:00
Downloading regex-2023.10.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (773 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 773.9/773.9 kB 6.0 MB/s eta 0:00:00a 0:00:01m
Downloading safetensors-0.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 4.0 MB/s eta 0:00:0000:0100:01
Downloading tokenizers-0.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 5.4 MB/s eta 0:00:0000:0100:01
Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 4.4 MB/s eta 0:00:00
Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
Downloading fsspec-2023.12.2-py3-none-any.whl (168 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.0/169.0 kB 5.6 MB/s eta 0:00:00
Installing collected packages: tqdm, safetensors, regex, fsspec, filelock, huggingface-hub, tokenizers, transformers
Successfully installed filelock-3.13.1 fsspec-2023.12.2 huggingface-hub-0.19.4 regex-2023.10.3 safetensors-0.4.1 tokenizers-0.15.0 tqdm-4.66.1 transformers-4.36.1

In [2]:
!pip install torch

Defaulting to user installation because normal site-packages is not writeable
Collecting torch
  Downloading torch-2.1.2-cp310-cp310-manylinux1_x86_64.whl.metadata (25 kB)
Requirement already satisfied: filelock in /home/ntkong/.local/lib/python3.10/site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions in /home/ntkong/.local/lib/python3.10/site-packages (from torch) (4.1.1)
Collecting sympy (from torch)
  Downloading sympy-1.12-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 2.0 MB/s eta 0:00:0000:0100:01
Collecting networkx (from torch)
  Downloading networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting jinja2 (from torch)
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 1.8 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: fsspec in /home/ntkong/.local/lib/python3.10/site-packages (from torch) (2023.12.2)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 4.9 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 5.6 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 6.5 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch)
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch)
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.6 MB/s eta 0:00:0000:0100:02
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch)
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 4.5 MB/s eta 0:00:0000:0100:01
Collecting nvidia-curand-cu12==10.3.2.106 (from torch)
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 5.7 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch)
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 4.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch)
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 4.0 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nccl-cu12==2.18.1 (from torch)
  Downloading nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl (209.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.8/209.8 MB 3.6 MB/s eta 0:00:0000:0100:02
Collecting nvidia-nvtx-cu12==12.1.105 (from torch)
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 4.0 MB/s eta 0:00:00
Collecting triton==2.1.0 (from torch)
  Downloading triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch)
  Downloading nvidia_nvjitlink_cu12-12.3.101-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ntkong/.local/lib/python3.10/site-packages (from jinja2->torch) (2.1.3)
Collecting mpmath>=0.19 (from sympy->torch)
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 4.5 MB/s eta 0:00:0000:0100:01
Downloading torch-2.1.2-cp310-cp310-manylinux1_x86_64.whl (670.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 3.1 MB/s eta 0:00:0000:0100:03m
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 1.6 MB/s eta 0:00:0000:0100:03m
Downloading triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.2/89.2 MB 4.6 MB/s eta 0:00:0000:0100:01m
Downloading networkx-3.2.1-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 6.3 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvjitlink_cu12-12.3.101-py3-none-manylinux1_x86_64.whl (20.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.5/20.5 MB 6.7 MB/s eta 0:00:0000:0100:01
Installing collected packages: mpmath, triton, sympy, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, jinja2, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch
Successfully installed jinja2-3.1.2 mpmath-1.3.0 networkx-3.2.1 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.18.1 nvidia-nvjitlink-cu12-12.3.101 nvidia-nvtx-cu12-12.1.105 sympy-1.12 torch-2.1.2 triton-2.1.0

In [7]:
from transformers import BertForSequenceClassification
import torch

bert_model = BertForSequenceClassification.from_pretrained('bert-base-uncaseed', num_labels=2,
    output_attentions=False,
    output_hidden_states=False)
optimizer = torch.optim.Adam(bert_model.parameters(), lr=2e-5)
loss_fn = torch.nn.CrossEntropyLoss()

ImportError:
BertForSequenceClassification requires the PyTorch library but it was not found in your environment.
However, we were able to find a TensorFlow installation. TensorFlow classes begin
with "TF", but are otherwise identically named to our PyTorch classes. This
means that the TF equivalent of the class you tried to import would be "TFBertForSequenceClassification".
If you want to use TensorFlow, please use TF classes instead!

If you really do want to use PyTorch please go to
https://pytorch.org/get-started/locally/ and follow the instructions that
match your environment.

In [ ]:
bert_model.train()