<a href="https://colab.research.google.com/github/kong1032002/KLTN/blob/main/rugpull_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch

Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.1.0+cu121)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch) (2.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch) (1.3.0)

In [2]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.35.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.19.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.15.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2023.11.17)

In [3]:
!pwd

/content

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import pandas as pd;
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Dataset_v1.9.csv")
df.dropna(inplace=True)
df.head()

,id,Label,mint_count_per_week,burn_count_per_week,mint_ratio,swap_ratio,burn_ratio,mint_mean_period,swap_mean_period,burn_mean_period,swap_in_per_week,swap_out_per_week,swap_rate,lp_avg,lp_std,lp_creator_holding_ratio,lp_lock_ratio,token_burn_ratio,token_creator_holding_ratio,number_of_token_creation_of_creator
0,0x3cd1c0b98be4451ca51265bbaeb76cf7b31e1c02,False,44.071475,16.466820,0.148132,0.796520,0.055348,0.034508,0.074894,0.221980,100.871903,136.103828,0.741002,0.119760,0.126458,0.000000e+00,0.000000,0.000000e+00,1.302617e-01,1
1,0x0c52de7bb69edd144d58d772fab1cd196919f5ef,False,13.813171,6.316279,0.169770,0.752600,0.077630,0.040580,0.050907,0.083953,42.502064,18.732391,2.266527,0.332226,0.431320,0.000000e+00,0.000000,4.000000e-07,1.000000e-08,1
2,0xa00d47b4b304792eb07b09233467b690db847c91,False,27.366327,17.779613,0.068019,0.887790,0.044191,0.131459,0.384409,0.191228,165.965722,191.224332,0.867757,0.377358,4.649864,0.000000e+00,0.064726,0.000000e+00,0.000000e+00,1
3,0x114e40ba90e9d8b002bc6936e3299daa393017bb,False,10.559028,1.912477,0.056257,0.933553,0.010189,0.036312,0.077704,0.140362,90.398212,84.822399,1.065397,0.467290,4.754048,1.480000e-08,0.693921,3.748588e-03,0.000000e+00,1
4,0x40829a59080a12f16bb8fba22354a6a42c810aab,False,9.662390,6.450369,0.024123,0.959774,0.016104,0.088733,0.206316,0.171454,204.911119,179.530891,1.141202,0.476190,5.466877,0.000000e+00,0.790202,0.000000e+00,1.000000e-08,1

In [6]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df["Label"] = label_encoder.fit_transform(df["Label"])
df.head()

,id,Label,mint_count_per_week,burn_count_per_week,mint_ratio,swap_ratio,burn_ratio,mint_mean_period,swap_mean_period,burn_mean_period,swap_in_per_week,swap_out_per_week,swap_rate,lp_avg,lp_std,lp_creator_holding_ratio,lp_lock_ratio,token_burn_ratio,token_creator_holding_ratio,number_of_token_creation_of_creator
0,0x3cd1c0b98be4451ca51265bbaeb76cf7b31e1c02,0,44.071475,16.466820,0.148132,0.796520,0.055348,0.034508,0.074894,0.221980,100.871903,136.103828,0.741002,0.119760,0.126458,0.000000e+00,0.000000,0.000000e+00,1.302617e-01,1
1,0x0c52de7bb69edd144d58d772fab1cd196919f5ef,0,13.813171,6.316279,0.169770,0.752600,0.077630,0.040580,0.050907,0.083953,42.502064,18.732391,2.266527,0.332226,0.431320,0.000000e+00,0.000000,4.000000e-07,1.000000e-08,1
2,0xa00d47b4b304792eb07b09233467b690db847c91,0,27.366327,17.779613,0.068019,0.887790,0.044191,0.131459,0.384409,0.191228,165.965722,191.224332,0.867757,0.377358,4.649864,0.000000e+00,0.064726,0.000000e+00,0.000000e+00,1
3,0x114e40ba90e9d8b002bc6936e3299daa393017bb,0,10.559028,1.912477,0.056257,0.933553,0.010189,0.036312,0.077704,0.140362,90.398212,84.822399,1.065397,0.467290,4.754048,1.480000e-08,0.693921,3.748588e-03,0.000000e+00,1
4,0x40829a59080a12f16bb8fba22354a6a42c810aab,0,9.662390,6.450369,0.024123,0.959774,0.016104,0.088733,0.206316,0.171454,204.911119,179.530891,1.141202,0.476190,5.466877,0.000000e+00,0.790202,0.000000e+00,1.000000e-08,1

In [15]:
from sklearn.model_selection import train_test_split

features = df.iloc[:, 2:]
target = df['Label']
(x_train, x_test, y_train, y_test) = train_test_split(features, target, test_size=0.2, random_state=42)

In [21]:
from transformers import BertTokenizer
import torch

features_string = features.astype(str).apply(lambda x: ' '.join(x), axis=1)

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
inputs = tokenizer(features_string.tolist())

In [32]:
from transformers import BertTokenizer, BertForSequenceClassification
from torch.utils.data import DataLoader, TensorDataset
import torch

bert_model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [34]:
dataloader = DataLoader(features_string, shuffle=False)

In [42]:
for batch in dataloader:
  print(batch)

Streaming output truncated to the last 5000 lines.
['0.936511402 0.0 0.010869565 0.989130435 0.0 0.0 0.168483696 0.0 85.22253759 0.0 91.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.916115175 0.0 0.010869565 0.989130435 0.0 0.0 0.119323209 0.0 83.36648091 0.0 91.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.967734193 0.0 0.011235955 0.988764045 0.0 0.0 0.23684602 0.0 85.16060899 0.0 88.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.889559589 0.0 0.011764706 0.988235294 0.0 0.0 0.050075246 0.0 74.72300544 0.0 84.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.981853248 0.0 0.012987013 0.987012987 0.0 0.0 0.269905171 0.0 74.62084685 0.0 76.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.92929206 0.0 0.012987013 0.987012987 0.0 0.0 0.078751793 0.0 70.62619657 0.0 76.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.901661096 0.0 0.01369863 0.98630137 0.0 0.0 0.104711804 0.0 64.9195989 0.0 72.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.882014516 0.0 0.013888889 0.986111111 0.0 0.0 0.103123494 0.0 62.62303067 0.0 71.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.963456208 0.0 0.014084507 0.985915493 0.0 0.0 0.142807323 0.0 67.44193456 0.0 70.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.883083433 0.0 0.014285714 0.985714286 0.0 0.0 0.088344386 0.0 60.93275688 0.0 69.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.919520657 0.0 0.014925373 0.985074627 0.0 0.0 0.113443156 0.0 60.68836338 0.0 66.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.928082791 0.0 0.015151515 0.984848485 0.0 0.0 0.143942304 0.0 60.32538141 0.0 65.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.918879417 0.0 0.015384615 0.984615385 0.0 0.0 0.073904819 0.0 58.80828268 0.0 64.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.946379644 0.0 0.015625 0.984375 0.0 0.0 0.130679663 0.0 59.62191758 0.0 63.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.97485179 0.0 0.016129032 0.983870968 0.0 0.0 0.292654788 0.0 59.46595917 0.0 61.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.913621388 0.0 0.016393443 0.983606557 0.0 0.0 0.16407548 0.0 54.81728328 0.0 60.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.879847307 0.0 0.016666667 0.983333333 0.0 0.0 0.096086788 0.0 51.91099111 0.0 59.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.861378947 0.0 0.017241379 0.982758621 0.0 0.0 0.070409946 0.0 49.09859997 0.0 57.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.924575548 0.0 0.017857143 0.982142857 0.0 0.0 0.185921602 0.0 50.85165516 0.0 55.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.903128696 0.0 0.017857143 0.982142857 0.0 0.0 0.074885929 0.0 49.67207827 0.0 55.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.968709157 0.0 0.018518519 0.981481481 0.0 0.0 0.146754709 0.0 51.3415853 0.0 53.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.920102599 0.0 0.019230769 0.980769231 0.0 0.0 0.08153395 0.0 46.92523254 0.0 51.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.99347539 0.0 0.02 0.98 0.0 0.0 0.408610272 0.0 48.6802941 0.0 49.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.938329067 0.0 0.020408163 0.979591837 0.0 0.0 0.074113208 0.0 45.03979521 0.0 48.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.684145096 0.0 0.020408163 0.979591837 0.0 0.0 0.057849819 0.0 32.8389646 0.0 48.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.946766311 0.0 0.021276596 0.978723404 0.0 0.0 0.112509557 0.0 43.5512503 0.0 46.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.940517845 0.0 0.022727273 0.977272727 0.0 0.0 0.075712418 0.0 40.44226732 0.0 43.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.788042806 0.0 0.024390244 0.975609756 0.0 0.0 0.089911539 0.0 31.52171222 0.0 40.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.983582563 0.0 0.025 0.975 0.0 0.0 0.146111937 0.0 38.35971995 0.0 39.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.914551162 0.0 0.025641026 0.974358974 0.0 0.0 0.077564239 0.0 34.75294417 0.0 38.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.95017698 0.0 0.027027027 0.972972973 0.0 0.0 0.071138019 0.0 34.20637128 0.0 36.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.986603851 0.0 0.027777778 0.972222222 0.0 0.0 0.271675597 0.0 34.53113479 0.0 35.0 100.0 0.0 1.0 0.0 0.0 0.5 10']
['0.790033663 0.0 0.03125 0.96875 0.0 0.0 0.101681629 0.0 24.49104354 0.0 31.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.985037142 0.0 0.043478261 0.956521739 0.0 0.0 0.175900729 0.0 21.67081713 0.0 22.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.964242668 0.0 0.043478261 0.956521739 0.0 0.0 0.185036561 0.0 21.21333869 0.0 22.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.994380304 0.0 0.047619048 0.952380952 0.0 0.0 0.294031597 0.0 19.88760609 0.0 20.0 100.0 0.0 1.0 0.0 0.0 0.5 6']
['0.993509662 0.0 0.047619048 0.952380952 0.0 0.0 0.298911668 0.0 19.87019323 0.0 20.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.992581895 0.0 0.05 0.95 0.0 0.0 0.623451327 0.0 18.859056 0.0 19.0 100.0 0.0 1.0 0.0 0.0 0.5 2']
['0.994543822 0.0 0.052631579 0.947368421 0.0 0.0 0.334538879 0.0 17.9017888 0.0 18.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.97235821 0.0 0.052631579 0.947368421 0.0 0.0 0.340080265 0.0 17.50244778 0.0 18.0 100.0 0.0 1.0 0.0 0.0 0.5 3']
['0.995449047 0.0 0.055555556 0.944444444 0.0 0.0 0.205786618 0.0 16.92263379 0.0 17.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.974580027 0.0 0.055555556 0.944444444 0.0 0.0 0.341870048 0.0 16.56786045 0.0 17.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.995714542 0.0 0.058823529 0.941176471 0.0 0.0 0.210142144 0.0 15.93143267 0.0 16.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.99829491 0.0 0.083333333 0.916666667 0.0 0.0 0.446272991 0.0 10.98124401 0.0 11.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.993916207 0.0 0.083333333 0.916666667 0.0 0.0 0.444894652 0.0 10.93307828 0.0 11.0 100.0 0.0 1.0 0.0 0.0 0.5 2']
['0.991217043 0.0 0.045454545 0.954545455 0.0 0.0 0.345960067 0.0 19.82434087 0.991217043 10.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.995965418 0.0 0.1 0.9 0.0 0.0 0.473061224 0.0 8.963688761 0.0 9.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.997708635 0.0 0.125 0.875 0.0 0.0 0.515478762 0.0 6.983960448 0.0 7.0 100.0 0.0 1.0 0.0 0.0 0.5 2']
['0.998133451 0.0 0.142857143 0.857142857 0.0 0.0 0.383731211 0.0 5.988800705 0.0 6.0 100.0 0.0 1.0 0.0 0.0 0.5 10']
['0.9949283 0.0 0.142857143 0.857142857 0.0 0.0 0.397015894 0.0 5.969569802 0.0 6.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.988516343 0.0 0.076923077 0.923076923 0.0 0.0 0.261315115 0.0 10.87367977 0.988516343 5.5 100.0 0.0 1.0 0.0 0.0 0.5 2']
['0.99697183 0.0 0.083333333 0.916666667 0.0 0.0 0.287969516 0.0 9.969718299 0.99697183 5.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.996155709 0.0 0.2 0.8 0.0 0.0 0.385175664 0.0 3.984622834 0.0 4.0 100.0 0.0 1.0 0.0 0.0 0.5 2']
['0.99384761 0.0 0.2 0.8 0.0 0.0 0.390491453 0.0 3.97539044 0.0 4.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.991322649 0.0 0.2 0.8 0.0 0.0 0.315640348 0.0 3.965290595 0.0 4.0 100.0 0.0 1.0 0.0 0.0 0.5 2']
['0.990074698 0.0 0.2 0.8 0.0 0.0 0.298697015 0.0 3.96029879 0.0 4.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.98072919 0.0 0.2 0.8 0.0 0.0 0.289801414 0.0 3.922916761 0.0 4.0 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.986714915 0.0 0.035714286 0.964285714 0.0 0.0 0.335994105 0.0 21.70772812 4.933574574 3.666666667 100.0 0.0 1.0 0.0 0.0 0.5 3']
['0.993080619 0.0 0.058823529 0.941176471 0.0 0.0 0.502373042 0.0 12.91004804 2.979241857 3.25 100.0 0.0 1.0 0.0 0.0 0.5 11']
['0.902278522 0.0 0.058823529 0.941176471 0.0 0.0 0.655847824 0.0 11.72962078 2.706835565 3.25 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.984218012 0.0 0.125 0.875 0.0 0.0 0.277789235 0.0 5.905308073 0.984218012 3.0 100.0 0.0 1.0 0.0 0.0 0.5 5']
['0.991091971 0.0 0.111111111 0.888888889 0.0 0.0 0.282192789 0.0 5.946551826 1.982183942 2.0 100.0 0.0 1.0 0.0 0.0 0.5 3']
['0.998789496 0.0 0.0625 0.9375 0.0 0.0 0.297407913 0.0 9.987894962 4.993947481 1.666666667 100.0 0.0 1.0 0.0 0.0 0.5 4']
['0.998375659 0.0 0.125 0.875 0.0 0.0 0.548780488 0.0 4.991878293 1.996751317 1.666666667 100.0 0.0 1.0 0.0 0.0 0.5 3']
['0.992261085 0.0 0.125 0.875 0.0 0.0 0.382870469 0.0 4.961305427 1.984522171 1.666666667 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.998411918 0.0 0.024390244 0.975609756 0.0 0.0 0.354469854 0.0 24.96029794 14.97617876 1.5625 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.97300741 0.0 0.024390244 0.975609756 0.0 0.0 0.169746096 0.0 24.32518525 14.59511115 1.5625 100.0 0.0 1.0 0.0 0.0 0.5 1']
['0.98769787 0.0 0.066666667 0.933333333 0.0 0.0 0.123987787 0.0 6.913885092 6.913885092 0.875 100.0 0.0 1.0 0.0 0.0 0.5 2']
['0.992607959 0.0 0.033333333 0.966666667 0.0 0.0 0.275976909 0.0 21.8373751 6.948255715 2.75 100.0 0.0 1.0 0.0 0.5 0.5 18']
['0.9025128 0.0 0.01010101 0.98989899 0.0 0.0 0.148907836 0.0 88.44625438 0.0 98.0 100.0 0.0 1.0 0.0 0.0 0.500015521 1']
['0.864486582 0.0 0.008547009 0.991452991 0.0 0.0 0.074647174 0.0 100.2804436 0.0 116.0 100.0 0.0 1.0 0.0 0.0 0.500345545 1']
['0.973881679 0.0 0.045454545 0.954545455 0.0 0.0 0.218618989 0.0 17.52987021 2.921645036 4.5 100.0 0.0 1.0 0.0 0.0 0.500541804 1']
['0.188702381 0.188702381 0.000559597 0.998880806 0.000559597 0.0 0.014267491 1.0 156.2455714 180.5881786 0.864300626 100.0 0.0 1.0 0.0 0.084788895 0.501712532 1']
['0.927030101 0.0 0.001531394 0.998468606 0.0 0.0 0.130844851 0.0 604.4236258 0.0 652.0 100.0 0.0 1.0 0.0 0.0 0.503487775 1']
['0.893392617 0.0 0.008196721 0.991803279 0.0 0.0 0.068144658 0.0 108.1005067 0.0 121.0 100.0 0.0 1.0 0.0 0.0 0.505061537 1']
['0.969218343 0.0 0.014492754 0.985507246 0.0 0.0 0.187526031 0.0 65.90684735 0.0 68.0 100.0 0.0 1.0 0.0 0.0 0.505683887 1']
['0.987414062 0.0 0.010638298 0.989361702 0.0 0.0 0.374367622 0.0 77.01829687 14.81121094 4.875 100.0 0.0 1.0 0.0 0.0 0.505967513 2']
['0.958733863 0.0 0.043478261 0.956521739 0.0 0.0 0.302281807 0.0 14.38100794 6.711137038 1.875 100.0 0.0 1.0 0.0 0.0 0.5072 1']
['0.99948109 0.0 0.142857143 0.857142857 0.0 0.0 0.525477707 0.0 5.996886537 0.0 6.0 100.0 0.0 1.0 0.0 0.0 0.511072625 1']
['2.721643546 2.721643546 0.024390244 0.951219512 0.024390244 0.092036342 0.366787377 0.281524832 75.29880478 30.84529352 2.371428571 100.0 0.0 1.0 0.0 0.0 0.511394698 1']
['4.815524333 0.963104867 0.064935065 0.922077922 0.012987013 0.119513143 0.177866977 0.241443308 68.38044553 0.0 71.0 100.0 0.0 1.0 0.0 0.0 0.514382041 1']
['0.994812107 0.0 0.022727273 0.977272727 0.0 0.0 0.413126189 0.0 31.83398744 10.94293318 2.666666667 100.0 0.0 1.0 0.0 0.0 0.515550217 1']
['0.978020414 0.0 0.002409639 0.997590361 0.0 0.0 0.471306651 0.0 376.5378595 28.36259201 12.83333333 100.0 0.0 1.0 0.0 0.006355191 0.520274219 3']
['0.912034237 0.0 0.007575758 0.992424242 0.0 0.0 0.319836113 0.0 98.49969765 20.97678746 4.5 100.0 0.0 1.0 0.0 0.0 0.522 3']
['0.999600028 0.0 0.142857143 0.857142857 0.0 0.0 0.297520661 0.0 1.999200056 3.998400111 0.4 100.0 0.0 1.0 0.0 0.0 0.523809524 8']
['0.999005619 0.0 0.142857143 0.857142857 0.0 0.0 0.418604651 0.0 2.997016858 2.997016858 0.75 100.0 0.0 1.0 0.0 0.0 0.533333333 1']
['0.997345031 0.0 0.04 0.96 0.0 0.0 0.442857143 0.0 18.94955558 4.986725153 3.166666667 100.0 0.0 1.0 0.0 0.0 0.535438913 1']
['0.967828658 0.0 0.022222222 0.977777778 0.0 0.0 0.37907879 0.0 40.64880366 1.935657317 14.0 100.0 0.0 1.0 0.0 0.0 0.535523664 1']
['0.870368611 0.0 0.027777778 0.972222222 0.0 0.0 0.265081374 0.0 24.37032112 6.09258028 3.5 100.0 0.0 1.0 0.0 0.0 0.536825162 2']
['0.972406674 0.0 0.026315789 0.973684211 0.0 0.0 0.234005361 0.0 30.14460691 5.834440046 4.428571429 100.0 0.0 1.0 0.0 0.0 0.5455 9']
['0.983793755 0.0 0.018867925 0.981132075 0.0 0.0 0.251430292 0.0 45.25451271 5.902762528 6.571428571 100.0 0.0 1.0 0.0 0.0 0.5499343 4']
['0.999533947 0.0 0.041666667 0.958333333 0.0 0.0 0.496453901 0.0 13.99347526 8.995805527 1.4 100.0 0.0 1.0 0.0 0.0 0.55 1']
['0.995973619 0.0 0.055555556 0.944444444 0.0 0.0 0.40408998 0.0 14.93960428 1.991947237 5.0 100.0 0.0 1.0 0.0 0.0 0.555555556 1']
['0.99786831 0.0 0.055555556 0.944444444 0.0 0.0 0.315789474 0.0 12.97228804 3.991473242 2.6 100.0 0.0 1.0 0.0 0.0 0.555555556 4']
['1.978520232 0.989260116 0.013245033 0.98013245 0.006622517 0.485531526 0.363539446 1.0 97.93675147 48.47374568 1.98 100.0 0.0 1.0 0.0 0.013417326 0.563449221 1']
['0.98052726 0.0 0.018181818 0.981818182 0.0 0.0 0.257180917 0.0 42.1626722 10.78579986 3.583333333 100.0 0.0 1.0 0.0 0.2 0.565542218 6']
['0.993963578 0.0 0.029411765 0.970588235 0.0 0.0 0.433705418 0.0 25.84305302 6.957745044 3.25 100.0 0.0 1.0 0.0 0.0 0.569293645 1']
['0.999462921 0.0 0.166666667 0.833333333 0.0 0.0 0.461538462 0.0 1.998925842 2.998388763 0.5 100.0 0.0 1.0 0.0 0.0 0.571428571 1']
['0.996001502 0.0 0.038461538 0.961538462 0.0 0.0 0.482701812 0.0 22.90803454 1.992003004 7.666666667 100.0 0.0 1.0 0.0 0.0 0.572600257 1']
['0.997830445 0.0 0.045454545 0.954545455 0.0 0.0 0.43878327 0.0 16.96311756 3.991321779 3.4 100.0 0.0 1.0 0.0 0.0 0.580533976 1']
['0.999720647 0.0 0.111111111 0.888888889 0.0 0.0 0.343195266 0.0 4.998603234 2.999161941 1.25 100.0 0.0 1.0 0.0 0.0 0.583333333 1']
['0.898965922 0.0 0.111111111 0.888888889 0.0 0.0 0.980153885 0.0 7.191727373 0.0 8.0 100.0 0.0 1.0 0.0 0.0 0.584032738 1']
['0.991654233 0.0 0.015625 0.984375 0.0 0.0 0.417878193 0.0 46.60774894 15.86646772 2.764705882 100.0 0.0 1.0 0.0 0.0 0.585637917 3']
['0.997346675 0.997346675 0.007407407 0.985185185 0.007407407 0.0 0.40770665 1.0 98.73732085 33.90978696 2.828571429 100.0 0.0 1.0 0.0 0.0 0.587792912 3']
['0.993548832 0.0 0.047619048 0.952380952 0.0 0.0 0.420422715 0.0 17.88387898 1.987097664 6.0 100.0 0.0 1.0 0.0 0.0 0.588973944 1']
['0.994108984 0.0 0.029411765 0.970588235 0.0 0.0 0.188895089 0.0 32.80559647 0.0 33.0 100.0 0.0 1.0 0.0 0.35 0.59 1']
['0.999286224 0.0 0.027777778 0.972222222 0.0 0.0 0.55787037 0.0 23.98286938 10.99214847 2.0 100.0 0.0 1.0 0.0 0.0 0.592608696 1']
['1.991199609 0.0 0.027027027 0.972972973 0.0 0.074448186 0.41301908 0.0 60.73158807 10.95159785 5.083333333 100.0 0.0 1.0 0.0 0.0 0.594971932 2']
['0.952927163 0.0 0.02173913 0.97826087 0.0 0.0 0.076248494 0.0 42.88172233 0.0 45.0 100.0 0.0 1.0 0.0 0.0 0.596344904 1']
['0.994019121 0.0 0.047619048 0.952380952 0.0 0.0 0.345699368 0.0 16.89832506 2.982057363 4.25 100.0 0.0 1.0 0.0 0.0 0.6 1']
['0.998631175 0.0 0.019230769 0.980769231 0.0 0.0 0.53437877 0.0 41.94250936 8.987680577 4.2 100.0 0.0 1.0 0.0 0.0 0.6 1']
['0.943419772 0.0 0.037037037 0.962962963 0.0 0.0 0.290471989 0.0 24.52891407 0.0 26.0 100.0 0.0 1.0 0.0 0.0 0.6 1']
['0.998423455 0.0 0.111111111 0.888888889 0.0 0.0 0.460732984 0.0 6.988964185 0.998423455 3.5 100.0 0.0 1.0 0.0 0.0 0.6 1']
['0.993937442 0.0 0.032258065 0.967741935 0.0 0.0 0.386554622 0.0 23.8544986 5.963624651 3.428571429 100.0 0.0 1.0 0.0 0.0 0.6 1']
['0.967396746 0.0 0.052631579 0.947368421 0.0 0.0 0.194524849 0.0 8.706570716 8.706570716 0.9 100.0 0.0 1.0 0.0 0.0 0.6 1']
['0.999831378 0.0 0.333333333 0.666666667 0.0 0.0 1.0 0.0 0.999831378 0.999831378 0.5 100.0 0.0 1.0 0.0 0.0 0.6 1']
['0.991088723 0.0 0.034482759 0.965517241 0.0 0.0 0.466531813 0.0 22.79504062 4.955443614 3.833333333 100.0 0.0 1.0 0.0 0.0 0.60203278 1']
['0.938819924 0.0 0.090909091 0.909090909 0.0 0.0 0.330779185 0.0 8.44937932 0.938819924 4.5 100.0 0.0 1.0 0.0 0.0 0.614502466 2']
['0.953362779 0.0 0.037037037 0.962962963 0.0 0.0 0.100419117 0.0 20.97398114 3.813451117 4.4 100.0 0.0 1.0 0.0 0.0 0.614751936 1']
['0.037719579 0.0 0.024390244 0.975609756 0.0 0.0 0.194918011 0.0 0.603513272 0.905269908 0.64 100.0 0.0 1.0 0.0 0.0 0.62732029 1']
['0.971126333 0.0 0.125 0.875 0.0 0.0 0.474641308 0.0 5.826757999 0.971126333 3.0 100.0 0.0 1.0 0.0 0.0 0.648 1']
['0.993411748 0.0 0.071428571 0.928571429 0.0 0.0 0.365245575 0.0 4.967058742 7.947293988 0.555555556 100.0 0.0 1.0 0.0 0.0 0.652499917 10']
['0.976452449 0.0 0.019607843 0.980392157 0.0 0.0 0.228042509 0.0 36.12874061 12.69388183 2.642857143 100.0 0.0 1.0 0.0 0.0 0.657532811 1']
['0.992192716 0.0 0.045454545 0.954545455 0.0 0.0 0.44988443 0.0 14.88289075 5.953156298 2.142857143 100.0 0.0 1.0 0.0 0.0 0.659760084 1']
['0.846268262 1.269402393 0.006451613 0.983870968 0.009677419 0.002421974 0.044799851 0.342187223 70.66339988 58.39251008 1.201438849 100.0 0.0 1.0 0.0 0.0 0.663961327 1']
['0.949938194 0.0 0.010204082 0.989795918 0.0 0.0 0.155272488 0.0 58.89616805 33.2478368 1.722222222 100.0 0.0 1.0 0.0 0.0 0.670779793 21']
['0.999489348 0.0 0.142857143 0.857142857 0.0 0.0 0.621359223 0.0 4.997446741 0.999489348 2.5 100.0 0.0 1.0 0.0 0.0 0.67318339 1']
['0.936463549 0.0 0.021276596 0.978723404 0.0 0.0 0.082443827 0.0 34.64915133 8.428171945 3.7 100.0 0.0 1.0 0.0 0.0 0.6833488 2']
['0.954542441 0.0 0.012658228 0.987341772 0.0 0.0 0.39896535 0.0 61.09071625 13.36359418 4.266666667 100.0 0.0 1.0 0.0 0.0 0.6925 1']
['0.990794847 0.0 0.032258065 0.967741935 0.0 0.0 0.308951771 0.0 25.76066603 3.96317939 5.2 100.0 0.0 1.0 0.0 0.0 0.693037185 1']
['0.999461269 0.0 0.2 0.8 0.0 0.0 0.895705521 0.0 2.998383808 0.999461269 1.5 100.0 0.0 1.0 0.0 0.0 0.698008794 2']
['0.955198234 0.0 0.142857143 0.857142857 0.0 0.0 0.176402157 0.0 5.731189402 0.0 6.0 100.0 0.0 1.0 0.0 0.0 0.7 1']
['0.987065976 0.0 0.2 0.8 0.0 0.0 0.301072555 0.0 3.948263903 0.0 4.0 100.0 0.0 1.0 0.0 0.0 0.7 7']
['0.971379011 0.0 0.333333333 0.666666667 0.0 0.0 0.553703704 0.0 1.942758023 0.0 2.0 100.0 0.0 1.0 0.0 0.0 0.7 7']
['0.923186826 0.0 0.011363636 0.988636364 0.0 0.0 0.077004094 0.0 63.69989101 16.61736287 3.631578947 100.0 0.0 1.0 0.0 0.0 0.702610555 12']
['0.992171556 0.0 0.005780347 0.994219653 0.0 0.0 0.385373009 0.0 136.9196748 33.73383292 3.942857143 100.0 0.0 1.0 0.0 0.0 0.70375714 57']
['0.993188253 0.0 0.024390244 0.975609756 0.0 0.0 0.332931533 0.0 30.78883583 8.938694273 3.1 100.0 0.0 1.0 0.0 0.0 0.70471 24']
['0.998446531 0.0 0.166666667 0.833333333 0.0 0.0 0.40063762 0.0 3.993786123 0.998446531 2.0 100.0 0.0 1.0 0.0 0.0 0.705882353 1']
['1.788827812 0.0 0.036363636 0.963636364 0.0 0.005798563 0.066977604 0.0 47.40393702 0.0 53.0 100.0 0.0 1.0 0.0 0.0 0.706906814 1']
['0.997920998 0.0 0.045454545 0.954545455 0.0 0.0 0.418253968 0.0 16.96465696 3.991683992 3.4 100.0 0.0 1.0 0.0 0.0 0.71011273 1']
['0.987546271 0.0 0.047619048 0.952380952 0.0 0.0 0.417988724 0.0 13.82564779 5.925277625 2.0 100.0 0.0 1.0 0.0 0.0 0.713110895 1']
['0.990871141 0.0 0.047619048 0.952380952 0.0 0.0 0.387114142 0.0 13.87219597 5.945226845 2.0 100.0 0.0 1.0 0.0 0.0 0.713226651 15']
['0.999053476 0.0 0.166666667 0.833333333 0.0 0.0 0.528795812 0.0 4.995267381 0.0 5.0 100.0 0.0 1.0 0.0 0.0 0.717048353 1']
['0.892762249 0.0 0.017241379 0.982758621 0.0 0.0 0.07031164 0.0 34.81772771 16.06972048 2.052631579 100.0 0.0 1.0 0.0 0.0 0.72105 9']
['1.919771456 0.959885728 0.285714286 0.571428571 0.142857143 0.499980218 0.108090999 0.996597428 3.839542912 0.0 4.0 100.0 0.0 1.0 0.0 0.0 0.725528504 1']
['0.498563169 1.495689506 0.011235955 0.95505618 0.033707865 0.0 0.088534012 0.999879991 18.44683724 23.9310321 0.755102041 100.0 0.0 1.0 0.0 0.0 0.729711168 2']
['0.99708524 0.0 0.076923077 0.923076923 0.0 0.0 0.301470588 0.0 10.96793764 0.99708524 5.5 100.0 0.0 1.0 0.0 0.0 0.732377993 26']
['1.993102573 0.996551287 0.2 0.7 0.1 0.165790731 0.502150024 0.197802198 3.986205147 2.98965386 1.0 100.0 0.0 1.0 0.0 0.0 0.738325329 11']
['0.969886686 0.0 0.017857143 0.982142857 0.0 0.0 0.430184258 0.0 42.67501419 10.66875355 3.666666667 100.0 0.0 1.0 0.0 0.0 0.7425 1']
['0.938758721 0.0 0.03125 0.96875 0.0 0.0 0.374299835 0.0 22.53020931 6.571311049 3.0 100.0 0.0 1.0 0.0 0.0 0.744776788 1']
['0.999025422 0.999025422 0.071428571 0.857142857 0.071428571 0.0 0.622033898 0.6 11.98830506 0.0 12.0 100.0 0.0 1.0 0.0 0.0 0.745801256 21']
['0.241424115 0.0 0.043478261 0.956521739 0.0 0.0 0.379588336 0.0 1.207120574 4.104209953 0.277777778 100.0 0.0 1.0 0.0 0.0 0.746949957 1']
['0.894985683 1.789971366 0.005747126 0.982758621 0.011494253 0.0 0.4953005 0.354104136 118.1381101 34.90444163 3.3 100.0 0.0 1.0 0.0 0.0 0.746989685 1']
['0.972800824 0.0 0.021276596 0.978723404 0.0 0.0 0.420520402 0.0 36.96643129 7.782406588 4.222222222 100.0 0.0 1.0 0.0 0.0 0.7475 1']
['0.991137448 0.0 0.045454545 0.954545455 0.0 0.0 0.468010355 0.0 16.84933662 3.964549793 3.4 100.0 0.0 1.0 0.0 0.0 0.75 1']
['0.997185523 0.0 0.071428571 0.928571429 0.0 0.0 0.612770943 0.0 9.97185523 2.991556569 2.5 100.0 0.0 1.0 0.0 0.0 0.75 1']
['0.995963778 0.0 0.052631579 0.947368421 0.0 0.0 0.526723786 0.0 12.94752911 4.979818889 2.166666667 100.0 0.0 1.0 0.0 0.0 0.75 1']
['0.998870325 0.0 0.083333333 0.916666667 0.0 0.0 0.374269006 0.0 7.990962602 2.996610976 2.0 100.0 0.0 1.0 0.0 0.0 0.75 1']

In [40]:
from torch.nn import CrossEntropyLoss
from torch.optim import AdamW

# Define loss function and optimizer
criterion = CrossEntropyLoss()
optimizer = AdamW(bert_model.parameters())

# Training loop (example)
for epoch in range(10):
    for batch in dataloader:
        input_ids = batch
        labels = y_train  # replace with actual labels

        outputs = bert_model(input_ids, labels=labels)
        loss = outputs.loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

TypeError: ignored